version: '3.3'

services:
  neo4j:
    restart: always
    image: neo4j:2.3.2
    container_name: neo4j
    #  net: ${NETWORK}
    environment:
      - NEO4J_AUTH=none
      - elastic="http://elastic_container"
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/plugins:/plugins
      - ./neo4j/data/import:/data/import
    ports:
      - "7474:7474"
  elastic:
    image: elasticsearch:2.2.2
    restart: always
    #  net: ${NETWORK}
    container_name: elastic_container
    ports:
      - "9200:9200"
    volumes:
      - ./esdata:/data
      - ./elastic/plugins:/plugins
      - ./elastic/conf:/usr/share/elasticsearch/config
      - ./elastic/scripts:/usr/share/elasticsearch/config/scripts
    environment:
      - neo4j="http://neo4j"
    networks:
      - neo-elk
  kibana:
    image: kibana:4.4
    ports:
      - "5601:5601"
    networks:
      - neo-elk
    depends_on:
      - elastic

networks:
  neo-elk:
    driver: bridge
