version: '3.3'

services:
  neo4j:
    restart: always
    image: neo4j:3.5.21
      container_name: neo4j
      environment:
        - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
        - NEO4J_AUTH=neo4j/nimda
      #      - NEO4J_dbms_connector_http_listen__address=:7474
      #      - NEO4J_dbms_connector_https_listen__address=:6477
      #      - NEO4J_dbms_connector_bolt_listen__address=:7687
      #      - elastic="http://elastic_container"
      volumes:
        - $HOME/neo4j/data:/data
        - $HOME/neo4j/plugins:/plugins
        - $HOME/neo4j/conf:/conf
        - $HOME/neo4j/import:/imports
        - $HOME/neo4j/logs:/neologs
      ports:
        - 7474:7474
        #      - 6477:6477
        - 7687:7687
      networks:
        - neo-elk
  elastic:
    image: elasticsearch:2.2.2
    restart: always
    #  net: ${NETWORK}
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./esdata:/data
      - ./elastic/plugins:/plugins
      - ./elastic/conf:/usr/share/elasticsearch/config
      - ./elastic/scripts:/usr/share/elasticsearch/config/scripts
    environment:
      - neo4j="http://neo4j"
    networks:
      - neo-elk

networks:
  neo-elk:
    driver: bridge
